//
// Created by Muhammad Aditya Hilmy on 12/11/18.
//

#ifndef ENGIS_KITCHEN_EVENTS_H
#define ENGIS_KITCHEN_EVENTS_H

typedef enum {
    NEW_GAME, LOAD_GAME, START_GAME, SAVE_GAME, EXIT_GAME, GAME_OVER,
    UI_SET_NAME, UI_SET_LIFE, UI_SET_TIME, UI_SET_MONEY,
    GET_MAP_WIDTH, GET_MAP_HEIGHT, GET_TAB_MEJA, GET_TAB_FOOD, GET_RESTO_MATRIX, GET_KITCHEN_MATRIX,
    SET_MEJA_POSITIONS,
    COMMAND,
    LAST
} Event;

#define NO_OF_EVENTS LAST

typedef enum {
    CMD_GU, CMD_GD, CMD_GL, CMD_GR, CMD_LOAD, CMD_SAVE
} Commands;

#endif //ENGIS_KITCHEN_EVENTS_H
