//
// Created by Muhammad Aditya Hilmy on 12/11/18.
//

#ifndef ENGIS_KITCHEN_EVENTS_H
#define ENGIS_KITCHEN_EVENTS_H

typedef enum {
    NEW_GAME, LOAD_GAME, START_GAME, EXIT_GAME, GAME_OVER,
    UI_SET_NAME, UI_SET_LIFE, UI_SET_TIME, UI_SET_MONEY, UI_SET_FOODSTACK, UI_SET_CUSTQUEUE, UI_SET_ORDERLIST, UI_REFRESH_MAP,
    UI_GET_POINTED_MEJA, UI_GET_POINTED_FOOD,
    GET_MAP_WIDTH, GET_MAP_HEIGHT, GET_TAB_MEJA, GET_TAB_FOOD, GET_RESTO_MATRIX, GET_KITCHEN_MATRIX, GET_RESTO_DOOR_COORD, GET_KITCHEN_DOOR_COORD,
    IS_GAME_EXISTS,
    COMMAND,
    LAST
} Event;

#define NO_OF_EVENTS LAST

typedef enum {
    CMD_GU, CMD_GD, CMD_GL, CMD_GR, CMD_LOAD, CMD_SAVE, CMD_ORDER, CMD_TAKE, CMD_GIVE, CMD_PLACE, CMD_CLEARTRAY
} Commands;

#endif //ENGIS_KITCHEN_EVENTS_H
